feat: added swagger for api documentation
SE2Project-BHKPTZ/backend pull request #25
Opened 2024-04-15 16:57 UTC by OlgaKupar

The first working version. 

Planned **refactoring**:

 - Rebase Swagger annotations from "user.route.js" and "lobby.route.js" into a single "swagger.js" file.
 - Refactor "user.route.js" and "lobby.route.js" to match the updated Swagger annotations in "swagger.js".

2024-04-15 17:04 UTC, OlgaKupar commented on main.js
fix: to be done in the next commit

2024-04-15 20:18 UTC, OlgaKupar commented on swagger.js
I would appreciate any ideas on how to auto-format indentations for this specific annotation structure. 

Solution in worst case: remove all indentation spaces (but redability reduction).

2024-04-15 20:37 UTC, OlgaKupar commented on swagger.js
solved with npx eslint --fix <path_to_the_file>

2024-04-16 08:26 UTC, FRALEXAlexander requested changes

2024-04-16 08:26 UTC, FRALEXAlexander commented on src/routes/user.route.js
> + *     websocket: "ws://example.com/socket"
This should be the id of a socket not a url

2024-04-16 08:26 UTC, FRALEXAlexander commented on package.json
> +    "swagger": "^0.7.5",
This package add 35 vulnerabilities. I do not see where it is used it should be removed

2024-04-16 08:26 UTC, FRALEXAlexander commented on src/routes/lobby.route.js
> + *               description: The max number of players for the lobby (3, 4 or 6)
5 players is also valid

2024-04-16 08:26 UTC, FRALEXAlexander commented on swagger.js
> +      url: 'http://localhost:8080',
Change this to get the url of the running instance it will not always be localhost:8080

2024-04-17 09:16 UTC, FRALEXAlexander commented
Run your code before pushing to git

2024-04-17 14:32 UTC, FRALEXAlexander approved these changes
LGTM

2024-04-19 16:45 UTC, merged